Repository govau/design-system-starter, pull requests merged in 2019-08, with the labels that each got.

#159 Fix: spelling of header & format of Readme
  README.md
  docs/content/index.html
  docs/form/index.html
Labels: documentation

#160 Typo on header and add contents to readme
  README.md
  docs/content/index.html
  docs/form/index.html
Labels: documentation

#161 npm audit, update packages
  docs/css/main.css
  package-lock.json
Labels: security

#158 update metdata on all templates
  docs/content/index.html
  docs/form/index.html
  docs/index.html
Labels: enhancement

#166 updated metadata for current templates dev -> master
  docs/assets/favicons/designsystem.jpg
  docs/content/index.html
  docs/form/index.html
  docs/index.html
Labels: enhancement

#169 Add ci/cd dev --> master
  .circleci/config.yml
  .deploy/manifest-prod.yml
  .deploy/manifest-staging.yml
  .deploy/manifest-test.yml
  docs/css/main.css
Labels: devops

#170 Add build status to README
  README.md
Labels: documentation

#171 Update circle job names, add build status to readme
  .circleci/config.yml
  README.md
Labels: enhancement

#172 Add authentication to staging and test builds
  .circleci/config.yml
  .deploy/Staticfile.auth
Labels: ci/cd

#173 Add authentication to staging and test builds dev --> master
  .circleci/config.yml
  .deploy/Staticfile.auth
  README.md
Labels: ci/cd

#174 rename prod site
  .circleci/config.yml
  .deploy/manifest-prod.yml
  README.md
Labels: ci/cd

#179 add search, add novalidate attribute to form, update side-nav
  docs/content/index.html
  docs/css/main.css
  docs/form/index.html
  docs/index.html
  docs/js/script.min.js
  package-lock.json
  package.json
  src/sass/main.scss
Labels: enhancement

#180 reposition error messages
  docs/content/index.html
  docs/css/main.css
  docs/form/index.html
  docs/js/validate.js
Labels: enhancement
