Repository govau/design-system-starter, pull requests merged in 2019-02, with the labels that each got.

#68 Add link to content guide on basic page, update deps
  docs/basic/index.html
  docs/css/main.css
  package-lock.json
Labels: enhancement

#69 Add link to content guide on basic page, update deps
  docs/basic/index.html
  docs/css/main.css
  package-lock.json
Labels: documentation

#70 change from markdown to html link 😅
  docs/basic/index.html
Labels: documentation

#71 unclosed <a> tag
  docs/basic/index.html
Labels: documentation

#76 Fix for build scripts not running concurrently on windows
  package-lock.json
  package.json
Labels: bug

#97 bump dependencies, make windows scripts concurrent
  docs/css/main.css
  package-lock.json
  package.json
Labels: bug, enhancement
