Repository govau/design-system-starter, pull requests merged in 2019-04, with the labels that each got.

#120 Update markup for aria labels on footer and nav elements in DS Starter
  docs/basic/index.html
  docs/form/index.html
  docs/index.html
Labels: documentation

#121 Update markup for aria labels on footer and nav elements in DS Starter
  docs/basic/index.html
  docs/form/index.html
  docs/index.html
  package-lock.json
  package.json
Labels: accessibility, enhancement

#127 Add form validation, using form component
  docs/css/main.css
  docs/form/index.html
  docs/js/helper.js
  docs/js/validate.js
  package-lock.json
  package.json
  src/sass/main.scss
Labels: enhancement

#130 Update form page to use form component styles/layout
  README.md
  docs/css/main.css
  docs/form/index.html
  docs/js/helper.js
  docs/js/validate.js
  package-lock.json
  package.json
  src/sass/main.scss
Labels: accessibility, enhancement
